// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVWz8eBbTcvgt12T_wuv0dbn1sGz75zjg',
    appId: '1:457833193832:web:a6d9cbf1e27601cae5b6dd',
    messagingSenderId: '457833193832',
    projectId: 'kicscore-c42ee',
    authDomain: 'kicscore-c42ee.firebaseapp.com',
    storageBucket: 'kicscore-c42ee.firebasestorage.app',
    measurementId: 'G-96G8YLP5EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANihU-K5eAlbNW1wSxoYeCvM50h5d6HOo',
    appId: '1:457833193832:android:eed98250e5118d00e5b6dd',
    messagingSenderId: '457833193832',
    projectId: 'kicscore-c42ee',
    storageBucket: 'kicscore-c42ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-htoI8E4xAZ2HA_T36MX3qsW2Wut4_A',
    appId: '1:457833193832:ios:d97b58aa14d59b0ce5b6dd',
    messagingSenderId: '457833193832',
    projectId: 'kicscore-c42ee',
    storageBucket: 'kicscore-c42ee.firebasestorage.app',
    iosBundleId: 'com.example.fotgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-htoI8E4xAZ2HA_T36MX3qsW2Wut4_A',
    appId: '1:457833193832:ios:d97b58aa14d59b0ce5b6dd',
    messagingSenderId: '457833193832',
    projectId: 'kicscore-c42ee',
    storageBucket: 'kicscore-c42ee.firebasestorage.app',
    iosBundleId: 'com.example.fotgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVWz8eBbTcvgt12T_wuv0dbn1sGz75zjg',
    appId: '1:457833193832:web:de496d198c11a44fe5b6dd',
    messagingSenderId: '457833193832',
    projectId: 'kicscore-c42ee',
    authDomain: 'kicscore-c42ee.firebaseapp.com',
    storageBucket: 'kicscore-c42ee.firebasestorage.app',
    measurementId: 'G-37V81H2LLB',
  );
}
